############################################################################
# URDE appveyor build configuration
############################################################################
clone_depth: 1

platform:
  - x64

build_cloud: axiodl-macOS
image: macOS

build:
  verbosity: detailed

configuration:
  - Release

before_build:
  - cd $APPVEYOR_BUILD_FOLDER
  - git submodule update --init --recursive

build_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%CONFIGURATION% -GNinja ..
  - ninja urde

#notifications:
#  - provider: Slack
#    incoming_webhook:
#      secure: uoO0I0PWyCx0KLjBOG6d17aSVuEEvYztB/UiF8J0LmTb2O735mAdWcuZHTImDFUGZxeI34/qzOB2JKqF+h8dZA5yiprSTkWIookqQjUokAM=
#  - provider: Webhook
#    url: https://skyhook.glitch.me/api/webhooks/345359672326356993/M8kBYpqr1JyVNhnAHBwNN5TnZmtWy9_msxAQoeOlaa73UhPn8gLU5uYZCjU1qsAi3sGN/appveyor
#    method: POST
#    on_build_success: true
#    on_build_failure: true
#    on_build_status_changed: false

# Uncomment this to debug AppVeyor failures.
#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
